// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fastMeanFilter
NumericMatrix fastMeanFilter(NumericMatrix mat, int h);
RcppExport SEXP _sgp_fastMeanFilter(SEXP matSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(fastMeanFilter(mat, h));
    return rcpp_result_gen;
END_RCPP
}
// cpwdist
arma::mat cpwdist(arma::colvec locs1, arma::colvec locs2);
RcppExport SEXP _sgp_cpwdist(SEXP locs1SEXP, SEXP locs2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type locs1(locs1SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type locs2(locs2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpwdist(locs1, locs2));
    return rcpp_result_gen;
END_RCPP
}
// cinv
arma::mat cinv(arma::mat covmat);
RcppExport SEXP _sgp_cinv(SEXP covmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type covmat(covmatSEXP);
    rcpp_result_gen = Rcpp::wrap(cinv(covmat));
    return rcpp_result_gen;
END_RCPP
}
// cifelse
arma::mat cifelse(const arma::mat& d);
RcppExport SEXP _sgp_cifelse(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(cifelse(d));
    return rcpp_result_gen;
END_RCPP
}
// cifelse_eigvals
arma::mat cifelse_eigvals(arma::colvec eigvals, const double thresh);
RcppExport SEXP _sgp_cifelse_eigvals(SEXP eigvalsSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type eigvals(eigvalsSEXP);
    Rcpp::traits::input_parameter< const double >::type thresh(threshSEXP);
    rcpp_result_gen = Rcpp::wrap(cifelse_eigvals(eigvals, thresh));
    return rcpp_result_gen;
END_RCPP
}
// cgeteigs
arma::colvec cgeteigs(const arma::mat& Q);
RcppExport SEXP _sgp_cgeteigs(SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(cgeteigs(Q));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sgp_fastMeanFilter", (DL_FUNC) &_sgp_fastMeanFilter, 2},
    {"_sgp_cpwdist", (DL_FUNC) &_sgp_cpwdist, 2},
    {"_sgp_cinv", (DL_FUNC) &_sgp_cinv, 1},
    {"_sgp_cifelse", (DL_FUNC) &_sgp_cifelse, 1},
    {"_sgp_cifelse_eigvals", (DL_FUNC) &_sgp_cifelse_eigvals, 2},
    {"_sgp_cgeteigs", (DL_FUNC) &_sgp_cgeteigs, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_sgp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
