# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cinv <- function(covmat) {
    .Call(`_sgp_cinv`, covmat)
}

cMatern <- function(d, range, smoothness) {
    .Call(`_sgp_cMatern`, d, range, smoothness)
}

cifelse <- function(d) {
    .Call(`_sgp_cifelse`, d)
}

getQ <- function(maternmat, d, r) {
    .Call(`_sgp_getQ`, maternmat, d, r)
}

cgeteigs <- function(Q) {
    .Call(`_sgp_cgeteigs`, Q)
}

cifelse_eigvals <- function(eigvals, thresh) {
    .Call(`_sgp_cifelse_eigvals`, eigvals, thresh)
}

get_ldet <- function(Q) {
    .Call(`_sgp_get_ldet`, Q)
}

mod <- function(a, n) {
    .Call(`_sgp_mod`, a, n)
}

crun_sgp_nugget <- function(reps, n, p, tau, X, PLDs_precision, PLDs_ldet, errprec, precision_beta, y, iters, aas, bs, rhos, nus, tune_var, min_range, max_range, win_len, d, acpt_rhos, c0, c1, tune_k, acpt_chain, tune_var_chain) {
    .Call(`_sgp_crun_sgp_nugget`, reps, n, p, tau, X, PLDs_precision, PLDs_ldet, errprec, precision_beta, y, iters, aas, bs, rhos, nus, tune_var, min_range, max_range, win_len, d, acpt_rhos, c0, c1, tune_k, acpt_chain, tune_var_chain)
}

crun_sgp_correlated <- function(reps, n, p, tau, X, PLDs_precision, PLDs_ldet, PLDe_precision, PLDe_ldet, errprec, precision_beta, y, iters, aas, bs, rhos, nus, rhoe, nue, r, sd_r, tune_vars, tune_vare, min_range, max_range, win_len, d, acpt_rhos, acpt_rhoe, c0, c1, tune_k, acpt_chain, tune_var_chain) {
    .Call(`_sgp_crun_sgp_correlated`, reps, n, p, tau, X, PLDs_precision, PLDs_ldet, PLDe_precision, PLDe_ldet, errprec, precision_beta, y, iters, aas, bs, rhos, nus, rhoe, nue, r, sd_r, tune_vars, tune_vare, min_range, max_range, win_len, d, acpt_rhos, acpt_rhoe, c0, c1, tune_k, acpt_chain, tune_var_chain)
}

fastMeanFilter <- function(mat, h) {
    .Call(`_sgp_fastMeanFilter`, mat, h)
}

cpwdist <- function(locs1, locs2) {
    .Call(`_sgp_cpwdist`, locs1, locs2)
}

