# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastMeanFilter <- function(mat, h) {
    .Call(`_sgp_fastMeanFilter`, mat, h)
}

cpwdist <- function(locs1, locs2) {
    .Call(`_sgp_cpwdist`, locs1, locs2)
}

cinv <- function(covmat) {
    .Call(`_sgp_cinv`, covmat)
}

cifelse <- function(d) {
    .Call(`_sgp_cifelse`, d)
}

cifelse_eigvals <- function(eigvals, thresh) {
    .Call(`_sgp_cifelse_eigvals`, eigvals, thresh)
}

cgeteigs <- function(Q) {
    .Call(`_sgp_cgeteigs`, Q)
}

